# 6 вариант

# 32

Используя модуль array и библиотеку numpy, решить следующие задачи:
а) Дан целочисленный массив размера  𝑁
  Найти максимальное количество его одинаковых элементов.
б) Дана целочисленная матрица размера  𝑀×𝑁
  Найти количество ее столбцов, все элементы которых различны

In [23]:
import numpy as np

# a) 
print('Пункт а)')
N = int(input('Введите N: '))
massiv = np.random.randint(0, 10, (N, N)) # Создание случайной матрицы
_, count = np.unique(massiv, return_counts = True) # Получаем массив с количеством повторений элемента в массиве
print('Массив:')
print(massiv)
print('Максимальное количество одинаковых элементов:', max(count))
print()

# б)
print('Пункт б)')
N = int(input('Введите N: '))
M = int(input('Введите M: '))
massiv = np.random.randint(0, 10, (M, N)) # Создание случайной матрицы
count = sum([len(np.unique(massiv[:, i])) == M for i in range(N)])
print('Массив:')
print(massiv)
print('Количество столбцов, все элементы которых различны:', count)

Пункт а)
Введите N: 5
Массив:
[[3 7 5 8 8]
 [7 6 9 9 8]
 [3 6 7 6 0]
 [7 8 4 6 0]
 [6 1 6 4 0]]
Максимальное количество одинаковых элементов: 6

Пункт б)
Введите N: 5
Введите M: 5
Массив:
[[1 2 0 2 3]
 [4 1 8 5 0]
 [8 7 8 6 5]
 [6 6 4 0 9]
 [0 4 8 1 4]]
Количество столбцов, все элементы которых различны: 4


# 33

Дан стек и два элемента  𝐴
  и  𝐵
 . Необходимо удалить из стека все элементы, которые находятся между  𝐴
  и  𝐵
  (включая сами  𝐴
  и  𝐵
 ).

In [1]:
class Stack:
    # Инициализация класса Stack
    def __init__(self):
        self.items = []  # Создание пустого списка для хранения элементов стека

    # Метод для добавления элемента в стек
    def push(self, item):
        self.items.append(item)  # Добавляет элемент в конец списка

    # Метод для удаления и возвращения последнего элемента из стека
    def pop(self):
        return self.items.pop()  # Удаляет и возвращает последний элемент списка

    # Метод для получения последнего элемента стека без его удаления
    def peek(self):
        # Возвращает последний элемент, если стек не пустой; иначе возвращает None
        return self.items[-1] if not self.is_empty() else None

    # Метод для проверки, пуст ли стек
    def is_empty(self):
        return len(self.items) == 0  # Возвращает True, если список пуст, иначе False

    # Метод для получения количества элементов в стеке
    def size(self):
        return len(self.items)  # Возвращает количество элементов в списке

In [2]:
def remove_elements_between(stack, A, B):
    temp_stack = Stack()

    # Удаляем элементы до тех пор, пока не найдем B
    while not stack.is_empty() and stack.peek() != B:
        temp_stack.push(stack.pop())

    # Если найден B, удаляем его
    if not stack.is_empty():
        stack.pop()

    # Продолжаем удалять элементы, пока не найдем A
    while not stack.is_empty() and stack.peek() != A:
        stack.pop()

    # Если найден A, удаляем и его тоже
    if not stack.is_empty():
        stack.pop()

    # Возвращаем оставшиеся элементы обратно в основной стек в правильном порядке
    while not temp_stack.is_empty():
        stack.push(temp_stack.pop())

# Используем реализацию стека через список
stack = Stack()

# Добавляем элементы в стек
print("Стек до удаления элементов:")
for i in range(1, 11):
    stack.push(i)
    print (11 - i)

# Вызовем функцию удаления элементов между A=3 и B=7
remove_elements_between(stack, 3, 7)

print("Стек после удаления элементов между 3 и 7:")
while not stack.is_empty():
    print(stack.pop())

Стек до удаления элементов:
10
9
8
7
6
5
4
3
2
1
Стек после удаления элементов между 3 и 7:
10
9
8
2
1


# 34

In [10]:
class Queue:
    # Конструктор очереди
    def __init__(self):
        self.items = []  # Инициализация пустого списка для хранения элементов очереди

    # Метод для добавления элемента в конец очереди
    def enqueue(self, item):
        self.items.append(item)  # Добавляет элемент в конец списка

    # Метод для удаления элемента из начала очереди
    def dequeue(self):
        if not self.is_empty():   # Проверка, не пуста ли очередь
            return self.items.pop(0)  # Удаляет и возвращает первый элемент списка, если очередь не пуста
        return None  # Возвращает None, если очередь пуста

    # Метод для получения элемента в начале очереди без его удаления
    def peek(self):
        if not self.is_empty():  # Проверка, не пуста ли очередь
            return self.items[0]  # Возвращает первый элемент списка
        return None  # Возвращает None, если очередь пуста

    # Метод для проверки, пуста ли очередь
    def is_empty(self):
        return len(self.items) == 0  # Возвращает True, если в списке нет элементов

    # Метод для определения количества элементов в очереди
    def size(self):
        return len(self.items)  # Возвращает количество элементов в списке

In [11]:
class Node:
    # Конструктор узла, используемого для хранения данных в очереди
    def __init__(self, data=None):
        self.data = data  # Данные, хранящиеся в узле
        self.next = None  # Ссылка на следующий узел в очереди

class Queue:
    # Конструктор очереди
    def __init__(self):
        self.head = None  # Ссылка на начало (голову) очереди
        self.tail = None  # Ссылка на конец (хвост) очереди
        self._size = 0    # Счетчик размера очереди

    # Метод для добавления элемента в конец очереди
    def enqueue(self, item):
        new_node = Node(item)  # Создание нового узла с элементом
        if self.tail:  # Если очередь не пуста
            self.tail.next = new_node  # Связать последний узел с новым узлом
        self.tail = new_node  # Обновить хвост очереди
        if not self.head:  # Если очередь была пуста
            self.head = new_node  # Новый узел становится головой
        self._size += 1  # Увеличение размера очереди

    # Метод для удаления элемента из начала очереди
    def dequeue(self):
        if not self.is_empty():  # Проверка, не пуста ли очередь
            removed_data = self.head.data  # Сохранение данных удаляемого узла
            self.head = self.head.next  # Перемещение головы к следующему узлу
            if self.head is None:  # Если после удаления очередь пуста
                self.tail = None  # Очистить хвост очереди
            self._size -= 1  # Уменьшение размера очереди
            return removed_data  # Возврат данных удаляемого узла
        return None  # Возврат None, если очередь пуста

    # Метод для получения элемента на начале очереди без его удаления
    def peek(self):
        if not self.is_empty():  # Проверка, не пуста ли очередь
            return self.head.data  # Возвращение данных первого элемента
        return None  # Возврат None, если очередь пуста

    # Метод для проверки, пуста ли очередь
    def is_empty(self):
        return self.head is None  # True, если голова очереди None

    # Метод для определения размера очереди
    def size(self):
        return self._size  # Возвращение текущего размера очереди

In [12]:
class MinQueue:
    def __init__(self):
        self.queue = Queue()  # Основная очередь для хранения элементов
        self.mins = Queue()   # Вспомогательная очередь для хранения минимальных значений

    def enqueue(self, item):
        self.queue.enqueue(item)  # Добавление элемента в основную очередь
        # Удаление всех элементов из очереди минимумов, которые больше добавляемого элемента
        while not self.mins.is_empty() and self.mins.peek() > item:
            self.mins.dequeue()
        self.mins.enqueue(item)  # Добавление элемента в очередь минимумов

    def dequeue(self):
        item = self.queue.dequeue()  # Удаление элемента из основной очереди
        # Удаление элемента из очереди минимумов, если он равен удаляемому элементу из основной очереди
        if item == self.mins.peek():
            self.mins.dequeue()
        return item  # Возврат удаленного элемента

    def peek(self):
        return self.queue.peek()  # Просмотр первого элемента в основной очереди без его удаления

    def is_empty(self):
        return self.queue.is_empty()  # Проверка, пуста ли основная очередь

    def size(self):
        return self.queue.size()  # Получение количества элементов в основной очереди

    def get_min(self):
        if not self.mins.is_empty():
            return self.mins.peek()  # Получение минимального элемента
        return None  # Возврат None, если очередь минимумов пуста

# Создаем экземпляр MinQueue
q = MinQueue()

# Добавление элементов в очередь
q.enqueue(5)
print("Добавленно в конец очереди:", 5, "Минимально:", q.get_min())
q.enqueue(3)
print("Добавленно в конец очереди:", 3, "Минимально:", q.get_min())
q.enqueue(7)
print("Добавленно в конец очереди:", 7, "Минимально:", q.get_min())
q.enqueue(1)
print("Добавленно в конец очереди:", 1, "Минимально:", q.get_min())
q.enqueue(9)
print("Добавленно в конец очереди:", 9, "Минимально:", q.get_min())

# Удаление элементов и проверка минимального значения
print("Убрано из начала очереди:", q.dequeue(), "Минимально:", q.get_min())
print("Убрано из начала очереди:", q.dequeue(), "Минимально:", q.get_min())
print("Убрано из начала очереди:", q.dequeue(), "Минимально:", q.get_min())
print("Убрано из начала очереди:", q.dequeue(), "Минимально:", q.get_min())
print("Убрано из начала очереди:", q.dequeue(), "Минимально:", q.get_min())

Добавленно в конец очереди: 5 Минимально: 5
Добавленно в конец очереди: 3 Минимально: 3
Добавленно в конец очереди: 7 Минимально: 3
Добавленно в конец очереди: 1 Минимально: 1
Добавленно в конец очереди: 9 Минимально: 1
Убрано из начала очереди: 5 Минимально: 1
Убрано из начала очереди: 3 Минимально: 1
Убрано из начала очереди: 7 Минимально: 1
Убрано из начала очереди: 1 Минимально: 9
Убрано из начала очереди: 9 Минимально: None
